### PR TITLE
Update Dockerfile's Gradle Version

### PR DESCRIPTION
**Pull request by JRVilela**
Incrementing the Gradle version to 8.2

### CODE REVIEW

**Comment by JRVilela** [comment]
@mblomdahl  and @dsperling, we can make this the final version and merge into master if you would like. I don't see any further reason to keep it in a feature branch.

**Review by mblomdahl — APPROVED** [review]
Sounds good to me! Open a new PR to master when you're ready.

**Comment by mblomdahl** [comment]
@JRVilela I tried changing the base branch to master, and now it's a few stuff in the delta that I don't know how to assess. Is the current diff actual changes we should merge into master?

**Review by mblomdahl — CHANGES_REQUESTED** [review]
Please add changes from PR #3 and #4, to run as non-root user (#2).

**Pull request closed without merging**
